http:
  port: 8080
apiEndpoints:
  auth:
    host: localhost
    paths: ['/auth/*']
    methods: ["GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS"]

  catalogs:
    host: localhost
    paths: ['/catalogs', '/catalogs/*']
    methods: ["GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS"]

serviceEndpoints:
  nestjsService:
    url: 'http://backend:3000'

policies:
  - proxy
  - jwt
  - rate-limit
  - cors

pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - cors:
          action:
            origin: "*"
            methods: ["GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS"]
            allowedHeaders: "*"        
            preflightContinue: false
      - proxy:
          action:
            serviceEndpoint: nestjsService
            changeOrigin: true

  catalogs:
    apiEndpoints:
      - catalogs
    policies:
      - cors:
          action:
            origin: "*"
            methods: ["GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS"]
            allowedHeaders: "*"              
            preflightContinue: false
      - proxy:
          action:
            serviceEndpoint: nestjsService
            changeOrigin: true